services:
  postgres:
    image: postgres
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: actix
      POSTGRES_USER: actix
      POSTGRES_DB: actix
    ports:
      - "5432:5432"
volumes:
  pg_volume:
    name: pg_database
