name: Rust

on: push

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

  rust_fmt_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Format check
        run: cargo fmt --check
